# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'

  pod 'composeApp', :path => '../composeApp'

  pod("GoogleSignIn")

end